# Generated by Django 5.0.1 on 2026-02-12 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_childprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='childprofile',
            name='learning_style',
            field=models.CharField(choices=[('visual', 'Visual (Images/Videos)'), ('audio', 'Auditory (Sound/Music)'), ('kinesthetic', 'Activity-based (Interactive)')], default='visual', max_length=20),
        ),
        migrations.AddField(
            model_name='childprofile',
            name='reward_preference',
            field=models.CharField(choices=[('stars', 'Stars & Badges'), ('points', 'Points System'), ('visual', 'Animations & Fireworks')], default='stars', max_length=20),
        ),
        migrations.AddField(
            model_name='childprofile',
            name='sensory_mode',
            field=models.CharField(choices=[('low', 'Low Stimulation (Calm/Minimal)'), ('high', 'High Engagement (Vibrant/Active)'), ('neutral', 'Standard Mode')], default='neutral', max_length=20),
        ),
        migrations.AddField(
            model_name='childprofile',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='childprofile',
            name='diagnosis',
            field=models.CharField(blank=True, max_length=150, verbose_name='Primary Focus Area'),
        ),
        migrations.AlterField(
            model_name='childprofile',
            name='notes',
            field=models.TextField(blank=True, verbose_name='Sensory Triggers or Notes'),
        ),
    ]
