# Generated by Django 5.0.1 on 2026-02-13 06:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_user_is_approved'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('content_type', models.CharField(choices=[('video', 'Video Lesson'), ('audio', 'Audio/Sound Clip'), ('animation', 'Animated Content'), ('image_set', 'Image Set (for Activities)')], max_length=20)),
                ('activity_type', models.CharField(choices=[('none', 'General Lesson (No Game)'), ('matching', 'Matching Game'), ('sequencing', 'Sequencing Task'), ('shuffling', 'Card Shuffling'), ('drag_drop', 'Drag and Drop')], default='none', max_length=20)),
                ('file', models.FileField(upload_to='contributor_content/')),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='thumbnails/')),
                ('is_approved', models.BooleanField(default=False)),
                ('admin_feedback', models.TextField(blank=True, help_text='Feedback from Admin/Parents', null=True)),
                ('views_count', models.PositiveIntegerField(default=0)),
                ('completion_rate', models.FloatField(default=0.0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('contributor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
