# Generated by Django 5.0.1 on 2026-02-14 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_lesson'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='difficulty_level',
            field=models.CharField(default='beginner', max_length=20),
        ),
        migrations.AddField(
            model_name='lesson',
            name='skill_category',
            field=models.CharField(default='communication', max_length=50),
        ),
    ]
