# Generated by Django 5.0.1 on 2026-02-19 11:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_assignment'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name='childprofile',
            name='autism_percentage',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='childprofile',
            name='is_high_sensitivity',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='childprofile',
            name='reward_preference',
            field=models.CharField(default='stars', max_length=20),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='admin_feedback',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='content_type',
            field=models.CharField(choices=[('video', 'Video Lesson'), ('audio', 'Audio/Sound Clip'), ('animation', 'Animated Content'), ('image_set', 'Image Set')], max_length=20),
        ),
        migrations.CreateModel(
            name='ScreeningResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score_percentage', models.FloatField()),
                ('is_high_sensitivity', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('child', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='screening_tests', to='accounts.childprofile')),
            ],
        ),
    ]
