# Generated by Django 5.0.1 on 2026-02-21 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_notification_childprofile_autism_percentage_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lesson',
            name='activity_type',
        ),
        migrations.RemoveField(
            model_name='lesson',
            name='admin_feedback',
        ),
        migrations.RemoveField(
            model_name='lesson',
            name='completion_rate',
        ),
        migrations.RemoveField(
            model_name='lesson',
            name='views_count',
        ),
        migrations.AddField(
            model_name='lesson',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='lesson',
            name='duration_minutes',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='lesson',
            name='learning_objectives',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='lesson',
            name='target_age_group',
            field=models.CharField(default='primary', max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='lesson',
            name='content_type',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='difficulty_level',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='file',
            field=models.FileField(upload_to='lessons/files/'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='skill_category',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to='lessons/thumbs/'),
        ),
    ]
