# Generated by Django 5.0.1 on 2026-02-21 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_remove_lesson_activity_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='is_activity',
            field=models.BooleanField(default=False),
        ),
    ]
