# Generated by Django 5.0.1 on 2026-02-22 07:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_lesson_is_activity'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('completed_at', models.DateTimeField(auto_now_add=True)),
                ('stars_earned', models.IntegerField(default=1)),
                ('child', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.childprofile')),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.lesson')),
            ],
        ),
    ]
