# Generated by Django 5.0.1 on 2026-02-23 03:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_activityprogress'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='video_url',
            field=models.URLField(blank=True, help_text='Paste YouTube link here', null=True),
        ),
    ]
