# Generated by Django 5.0.1 on 2026-02-23 04:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_lesson_video_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='lessons/files/'),
        ),
    ]
