# Generated by Django 5.0.1 on 2026-03-08 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0016_notification_is_read_notification_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='admin_notes',
            field=models.TextField(blank=True, null=True),
        ),
    ]
