# Generated by Django 5.0.1 on 2026-03-08 14:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0017_lesson_admin_notes'),
    ]

    operations = [
        migrations.AddField(
            model_name='childprofile',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='child_profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('parent', 'Parent'), ('contributor', 'Contributor'), ('admin', 'Admin'), ('student', 'Student')], max_length=20),
        ),
    ]
