# Generated by Django 5.0.1 on 2026-03-09 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0018_childprofile_user_alter_user_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='childprofile',
            name='current_streak',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='childprofile',
            name='last_activity_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
