# Generated by Django 5.0.1 on 2026-03-09 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0019_childprofile_current_streak_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='childprofile',
            name='current_streak',
            field=models.PositiveIntegerField(default=0, help_text='Consecutive days of activity'),
        ),
    ]
