# Generated by Django 5.0.1 on 2026-03-09 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0020_alter_childprofile_current_streak'),
    ]

    operations = [
        migrations.AlterField(
            model_name='childprofile',
            name='last_activity_date',
            field=models.DateField(blank=True, help_text='The last date a lesson was completed', null=True),
        ),
    ]
