# Generated by Django 5.0.1 on 2026-03-11 05:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0021_alter_childprofile_last_activity_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='childprofile',
            name='autism_level',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='childprofile',
            name='diagnosis_type',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='childprofile',
            name='gender',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='childprofile',
            name='interests',
            field=models.TextField(blank=True, help_text='Comma separated interests'),
        ),
        migrations.AddField(
            model_name='childprofile',
            name='relationship_to_child',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='childprofile',
            name='sensory_sensitivity',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='user',
            name='certificate',
            field=models.FileField(blank=True, null=True, upload_to='certificates/'),
        ),
        migrations.AddField(
            model_name='user',
            name='experience_years',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='location',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='user',
            name='portfolio_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='user',
            name='qualification',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='user',
            name='specialization',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.CreateModel(
            name='BehaviorLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
                ('mood', models.CharField(max_length=50)),
                ('sleep_quality', models.CharField(max_length=50)),
                ('social_interaction', models.CharField(max_length=50)),
                ('meltdown_episodes', models.PositiveIntegerField(default=0)),
                ('attention_level', models.PositiveIntegerField()),
                ('child', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='behavior_logs', to='accounts.childprofile')),
            ],
        ),
    ]
