# Generated by Django 5.0.1 on 2026-03-14 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0023_user_profile_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='childprofile',
            name='diagnosis',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Primary Focus Area'),
        ),
    ]
