# Generated by Django 5.0.1 on 2026-03-14 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0024_alter_childprofile_diagnosis'),
    ]

    operations = [
        migrations.AddField(
            model_name='childprofile',
            name='child_photo',
            field=models.ImageField(blank=True, null=True, upload_to='profiles/'),
        ),
    ]
