# Generated by Django 5.0.1 on 2026-03-14 11:19

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0025_childprofile_child_photo'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='assignment',
            unique_together={('child', 'lesson', 'assigned_date')},
        ),
        migrations.RemoveField(
            model_name='childprofile',
            name='child_photo',
        ),
        migrations.AddField(
            model_name='assignment',
            name='completed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='assignment',
            name='child',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.childprofile'),
        ),
        migrations.AlterField(
            model_name='behaviorlog',
            name='attention_level',
            field=models.IntegerField(default=3),
        ),
        migrations.AlterField(
            model_name='behaviorlog',
            name='child',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.childprofile'),
        ),
        migrations.AlterField(
            model_name='behaviorlog',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='behaviorlog',
            name='meltdown_episodes',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='behaviorlog',
            name='mood',
            field=models.CharField(choices=[('calm', 'Calm'), ('energetic', 'Energetic'), ('anxious', 'Anxious'), ('tired', 'Tired')], max_length=20),
        ),
        migrations.AlterField(
            model_name='behaviorlog',
            name='sleep_quality',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='behaviorlog',
            name='social_interaction',
            field=models.CharField(max_length=20),
        ),
        migrations.RemoveField(
            model_name='assignment',
            name='iq_focus',
        ),
        migrations.RemoveField(
            model_name='assignment',
            name='target_mood',
        ),
    ]
