# Generated by Django 5.0.1 on 2026-03-14 15:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0026_alter_assignment_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignment',
            name='target_mood',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='assignment',
            name='child',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='accounts.childprofile'),
        ),
        migrations.AlterField(
            model_name='behaviorlog',
            name='child',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='behavior_logs', to='accounts.childprofile'),
        ),
        migrations.AlterField(
            model_name='behaviorlog',
            name='social_interaction',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
