# Generated by Django 5.0.1 on 2026-03-15 05:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0027_assignment_target_mood_alter_assignment_child_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='childprofile',
            name='child_photo',
            field=models.ImageField(blank=True, null=True, upload_to='child_photos/'),
        ),
        migrations.AddField(
            model_name='lesson',
            name='activity_type',
            field=models.CharField(choices=[('none', 'General Lesson (No Game)'), ('matching', 'Matching Game'), ('sequencing', 'Sequencing Task'), ('emotion', 'Emotion Recognition'), ('memory', 'Memory Game'), ('drag_drop', 'Drag and Drop')], default='none', max_length=20),
        ),
        migrations.AddField(
            model_name='user',
            name='data_privacy_agreed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='progress_tracking_permission',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='relationship_to_child',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='behaviorlog',
            name='mood',
            field=models.CharField(choices=[('calm', 'Calm'), ('energetic', 'Energetic'), ('anxious', 'Anxious'), ('tired', 'Tired'), ('Happy', 'Happy'), ('Anxious', 'Anxious'), ('Irritable', 'Irritable')], max_length=20),
        ),
        migrations.AlterField(
            model_name='behaviorlog',
            name='social_interaction',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='childprofile',
            name='interests',
            field=models.TextField(blank=True, help_text='Comma separated: Animals, Numbers, Music, Colors, Stories'),
        ),
        migrations.CreateModel(
            name='LearningPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='My Plan', max_length=100)),
                ('plan_type', models.CharField(choices=[('daily', 'Daily'), ('weekly', 'Weekly'), ('custom', 'Custom')], default='daily', max_length=20)),
                ('custom_difficulty', models.CharField(blank=True, max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('child', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='learning_plans', to='accounts.childprofile')),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='learning_plans', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='LearningPlanItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skill', models.CharField(max_length=100)),
                ('activity', models.CharField(max_length=255)),
                ('duration_minutes', models.PositiveIntegerField(default=5)),
                ('order', models.PositiveIntegerField(default=0)),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='accounts.learningplan')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='ParentReward',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stars_required', models.PositiveIntegerField()),
                ('reward_description', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('child', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rewards', to='accounts.childprofile')),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rewards', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['stars_required'],
            },
        ),
    ]
